# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=50)),
                ('father', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
                ('student_card', models.CharField(max_length=20)),
                ('group_name', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='group.Group')),
            ],
            options={
                'ordering': ['group_name', 'surname'],
            },
        ),
    ]
